import TokenType.*

val keywords = mapOf(
    // ========== LOX KEYWORDS ==========
    "and" to AND,
    "class" to CLASS,
    "else" to ELSE,
    "false" to FALSE,
    "fun" to FUN,
    "for" to FOR,
    "if" to IF,
    "nil" to NIL,
    "or" to OR,
    "print" to PRINT,
    "return" to RETURN,
    "super" to SUPER,
    "this" to THIS,
    "true" to TRUE,
    "var" to VAR,
    "while" to WHILE,

    // ========== TACSHOOTER DSL KEYWORDS ==========
    "GAME" to GAME,
    "AGENTS" to AGENTS,
    "AGENT" to AGENT,
    "ABILITIES" to ABILITIES,
    "ABILITY" to ABILITY,
    "WEAPONS" to WEAPONS,
    "WEAPON" to WEAPON,
    "MAP" to MAP,
    "SITES" to SITES,
    "SITE" to SITE,
    "TEAMS" to TEAMS,
    "TEAM" to TEAM,
    "ECONOMY" to ECONOMY,
    "STATUS_EFFECTS" to STATUS_EFFECTS,
    "EFFECT" to EFFECT,
    "MATCH" to MATCH,
    "TIMING" to TIMING,
    "OBJECTIVE" to OBJECTIVE,
    "BONUSES" to BONUSES,
    "ARMOR" to ARMOR,
    "DAMAGE" to DAMAGE,
    "CAST" to CAST,
    "ON_KILL" to ON_KILL,
    "ON_APPLY" to ON_APPLY,
    "ON_TICK" to ON_TICK,
    "ON_EXPIRE" to ON_EXPIRE,

    "stats" to STATS,
    "config" to CONFIG,
    "callouts" to CALLOUTS,
    "entries" to ENTRIES,
    "falloff" to FALLOFF,

    "AOE" to AOE,
    "SINGLE_TARGET" to SINGLE_TARGET,
    "MOBILITY" to MOBILITY,
    "OFFENSIVE" to OFFENSIVE,
    "DEFENSIVE" to DEFENSIVE,
    "UTILITY" to UTILITY,
    "SUPPORT" to SUPPORT,
    "CONTROL" to CONTROL,
    "BUFF" to BUFF,
    "DEBUFF" to DEBUFF,
    "NEUTRAL" to NEUTRAL,
    "PASSIVE" to PASSIVE,

    "ENEMY" to ENEMY,
    "ALLY" to ALLY,
    "SELF" to SELF,
    "ALL" to ALL,

    "yes" to YES,
    "no" to NO,
    "with" to WITH
)
